project:

  input_folder: input

  output_folder: output

  temp_folder: temp

  checkpoint_folder: checkpoint



tts:

  engine: mana

  device: cuda

  sample_rate: 24000

  speed: 1.0

  language: fa


  models:

    vits_fa:

      model_path: models/persian_vits/model.pth

      config_path: models/persian_vits/config.json

    f5:

      model: F5TTS_v1_Base


    xtts:

      model_path: models/xtts_v2


    mana:
      model_path: models/persian_vits



whisper:

  enabled: true

  model: small

  language: fa

  device: cuda





chunk:

  max_words: 80





quality:

  max_retry: 3

  min_similarity: 85





audio:

  format: wav

  bitrate: 192k